import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
const MAX_BYTES=1_500_000, MAX_REDIRECTS=3;
function privateIp(ip:string){if(ip.includes(":"))return ip==="::1"||ip.startsWith("fc")||ip.startsWith("fd")||ip.startsWith("fe80")||ip.startsWith("::ffff:127.");const p=ip.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127);}
async function safeUrl(raw:string){let u:URL;try{u=new URL(raw)}catch{throw new Error("Ce lien n’est pas valide.")}if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw new Error("Seuls les liens HTTP et HTTPS sont acceptés.");const host=u.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||isIP(host)&&privateIp(host))throw new Error("Cette adresse n’est pas autorisée.");let addresses;try{addresses=await lookup(host,{all:true})}catch{throw new Error("Ce site est introuvable.")}if(!addresses.length||addresses.some(a=>privateIp(a.address)))throw new Error("Cette adresse n’est pas autorisée.");return u;}
function decode(s:string){return s.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).trim()}
function meta(html:string,key:string){const tags=html.match(/<meta\s+[^>]*>/gi)||[];for(const tag of tags){const attrs:Record<string,string>={};tag.replace(/([\w:-]+)\s*=\s*["']([^"']*)["']/g,(_,k,v)=>(attrs[k.toLowerCase()]=v,""));if((attrs.property||attrs.name)?.toLowerCase()===key.toLowerCase())return decode(attrs.content||"")}return ""}
async function fetchPage(initial:URL){let url=initial;for(let i=0;i<=MAX_REDIRECTS;i++){url=await safeUrl(url.toString());const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);let res:Response;try{res=await fetch(url,{redirect:"manual",signal:controller.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; LesGirlzBot/1.0)",accept:"text/html,application/xhtml+xml"}})}finally{clearTimeout(timer)}if(res.status>=300&&res.status<400&&res.headers.get("location")){url=new URL(res.headers.get("location")!,url);continue}if(!res.ok)throw new Error("Ce site ne répond pas.");if(!(res.headers.get("content-type")||"").toLowerCase().includes("text/html"))throw new Error("Ce lien ne pointe pas vers une page web.");const declared=Number(res.headers.get("content-length")||0);if(declared>MAX_BYTES)throw new Error("Cette page est trop volumineuse.");const reader=res.body?.getReader();if(!reader)throw new Error("Contenu inaccessible.");let total=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>MAX_BYTES){await reader.cancel();throw new Error("Cette page est trop volumineuse.")}chunks.push(value)}return {html:new TextDecoder().decode(Buffer.concat(chunks)),url}}throw new Error("Trop de redirections.")}
export async function POST(req:Request){try{const sb=await createClient();const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:"Connexion requise."},{status:401});const body=await req.json();const initial=await safeUrl(String(body.url||""));const {html,url}=await fetchPage(initial);const title=meta(html,"og:title")||meta(html,"twitter:title")||decode(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"");const image=meta(html,"og:image")||meta(html,"twitter:image")||meta(html,"twitter:image:src");const imageUrl=image?new URL(image,url).toString():"";return NextResponse.json({url:url.toString(),title:title.slice(0,300),imageUrl,description:(meta(html,"og:description")||meta(html,"twitter:description")||meta(html,"description")).slice(0,1000),sourceName:(meta(html,"og:site_name")||url.hostname.replace(/^www\./,"")).slice(0,120),sourceDomain:url.hostname.replace(/^www\./,"")})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Impossible d’analyser ce lien."},{status:400})}}
