"use client";
import Link from "next/link";
import { useState } from "react";
import { deleteRecommendation, saveRecommendation } from "@/app/actions";
import { ArrowLeftIcon } from "@/components/icons";
import { CATEGORIES, CATEGORY_LABELS } from "@/lib/categories";
import type { Recommendation } from "@/lib/types";
export function EditForm({ item }: { item: Recommendation }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await saveRecommendation({ id: item.id, groupId: item.group_id, url: item.url, title: String(form.get("title")), imageUrl: String(form.get("imageUrl")), description: item.description || "", sourceName: item.source_name || "", sourceDomain: item.source_domain || "", category: String(form.get("category")), comment: String(form.get("comment")) }); location.href = "/"; } catch (caught) { setError(caught instanceof Error ? caught.message : "Erreur"); setBusy(false); } }
  return <main className="shell min-h-dvh px-5 py-6"><header className="flex items-center justify-between"><Link href="/" className="icon-button" aria-label="Retour"><ArrowLeftIcon /></Link><span className="text-[11px] uppercase tracking-[.13em]">Modifier le coup de cœur</span><span className="w-10" /></header><h1 className="serif mt-12 text-[34px]">Les détails</h1><form onSubmit={submit} className="mt-8 space-y-5"><div><label className="label">Titre</label><input className="field" name="title" required defaultValue={item.title} /></div><div><label className="label">Image URL</label><input className="field" name="imageUrl" type="url" defaultValue={item.image_url || ""} /></div><fieldset><legend className="label">Catégorie</legend><div className="grid grid-cols-2 gap-2">{CATEGORIES.map((category) => <label key={category}><input className="peer sr-only" type="radio" name="category" value={category} defaultChecked={item.category === category} /><span className="flex min-h-11 items-center justify-center rounded-[4px] border border-[var(--line)] text-xs peer-checked:border-[var(--ink)] peer-checked:bg-[var(--cream)]">{CATEGORY_LABELS[category]}</span></label>)}</div></fieldset><div><label className="label">Commentaire</label><textarea className="field" name="comment" defaultValue={item.comment || ""} /></div>{error && <p className="error">{error}</p>}<button disabled={busy} className="btn btn-primary">Enregistrer</button></form><form action={deleteRecommendation.bind(null, item.id)} className="mt-4"><button onClick={(event) => { if (!confirm("Supprimer ce coup de cœur ?")) event.preventDefault(); }} className="btn text-[var(--danger)]">Supprimer ce coup de cœur</button></form></main>;
}
