import Link from "next/link";
import type { ReactNode } from "react";

const iconClass = "h-[24px] w-[24px]";
function HomeIcon(){return <svg viewBox="0 0 24 24" className={iconClass} fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M3.5 10.5 12 3.5l8.5 7" strokeLinecap="round" strokeLinejoin="round"/><path d="M5.5 9.7V21h13V9.7M9.5 21v-6h5v6" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function BookIcon(){return <svg viewBox="0 0 24 24" className={iconClass} fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H11v17H7.5A3.5 3.5 0 0 0 4 22V5.5Z" strokeLinejoin="round"/><path d="M20 5.5A3.5 3.5 0 0 0 16.5 2H13v17h3.5A3.5 3.5 0 0 1 20 22V5.5Z" strokeLinejoin="round"/></svg>}
function WatchIcon(){return <svg viewBox="0 0 24 24" className={iconClass} fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M4 8h16v12H4z" strokeLinejoin="round"/><path d="m5 8 3-5h4L9 8m4 0 3-5h3l1 2-2 3" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function PlaceIcon(){return <svg viewBox="0 0 24 24" className={iconClass} fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M12 22s7-6.2 7-12A7 7 0 1 0 5 10c0 5.8 7 12 7 12Z" strokeLinejoin="round"/><circle cx="12" cy="10" r="2.4"/></svg>}
function NavItem({href,label,children}:{href:string;label:string;children:ReactNode}){return <Link href={href} aria-label={label} className="flex h-full items-center justify-center text-[#6f6864] transition-transform active:scale-90">{children}</Link>}
export function BottomNav(){return <nav className="sticky bottom-0 z-30 border-t border-[#eee8e2] bg-white px-3 pb-[max(8px,env(safe-area-inset-bottom))] pt-1.5"><div className="grid h-[64px] grid-cols-5 items-center"><NavItem href="/" label="Accueil"><HomeIcon/></NavItem><NavItem href="/?category=books" label="Livres"><BookIcon/></NavItem><Link href="/add" aria-label="Ajouter" className="mx-auto flex h-[56px] w-[56px] items-center justify-center rounded-full bg-[#2e0002] text-white"><span className="-mt-[3px] text-[34px] font-light leading-none">+</span></Link><NavItem href="/?category=watch" label="Films et séries"><WatchIcon/></NavItem><NavItem href="/?category=places" label="Adresses"><PlaceIcon/></NavItem></div></nav>}
